### ISSUE TITLE
AnimePahe isn't working

### ISSUE THREAD

**Issue by KiritoX1** [jmir1/aniyomi-extensions#1277]
### Source information and language

AnimePahe 13.17

### Steps to reproduce

Streaming and downloading are not working

### Expected behavior

Should stream and download anime properly 

### Actual behavior

Showing - 
      Expected start of the object '{', but had 'EOF' instead JSON input: not enough arguments
     

### Aniyomi version

0.12.3.10

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by devinbedari** [comment]
Managed to grab a stack trace of the error:
```
02-14 18:52:57.222 28396 28540 E StandaloneCoroutine: Expected start of the object '{', but had 'EOF' instead
02-14 18:52:57.222 28396 28540 E StandaloneCoroutine: JSON input: not enough arguments
02-14 18:52:57.222 28396 28540 E StandaloneCoroutine: kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the object '{', but had 'EOF' instead
02-14 18:52:57.222 28396 28540 E StandaloneCoroutine: JSON input: not enough arguments
02-14 18:52:57.222 28396 28540 E StandaloneCoroutine: 	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:1)
02-14 18:52:57.222 28396 28540 E StandaloneCoroutine: 	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:2)
02-14 18:52:57.222 28396 28540 E StandaloneCoroutine: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:1)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(AbstractJsonLexer.kt:2)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:4)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:9)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(StreamingJsonDecoder.kt:2)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:3)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:1)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at kotlinx.serialization.json.JsonObjectSerializer.deserialize(JsonElementSerializers.kt:3)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at kotlinx.serialization.json.JsonObjectSerializer.deserialize(JsonElementSerializers.kt:1)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:12)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:1)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:3)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at eu.kanade.tachiyomi.animeextension.en.animepahe.AnimePahe.videoListParse(AnimePahe.kt:337)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at eu.kanade.tachiyomi.ui.anime.AnimePresenter$$ExternalSyntheticLambda8.call(Unknown Source:46)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:1)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:3)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:4)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.Subscriber.setProducer(Subscriber.java:8)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:1)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.Subscriber.setProducer(Subscriber.java:6)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$$ExternalSyntheticLambda0.call(Unknown Source:5)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.Observable.unsafeSubscribe(Observable.java:2)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:2)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:1)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.Observable.unsafeSubscribe(Observable.java:2)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:4)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:1)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.Observable.unsafeSubscribe(Observable.java:2)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.internal.operators.OnSubscribeFlattenIterable.call(OnSubscribeFlattenIterable.java:5)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.internal.operators.OnSubscribeFlattenIterable.call(OnSubscribeFlattenIterable.java:1)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.Observable.unsafeSubscribe(Observable.java:2)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:4)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:1)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:4)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:1)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:4)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:1)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.Observable.unsafeSubscribe(Observable.java:2)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:2)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:1)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:4)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:1)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.Observable.subscribe(Observable.java:25)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at eu.kanade.tachiyomi.util.lang.RxCoroutineBridgeKt.awaitOne(RxCoroutineBridge.kt:4)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at eu.kanade.tachiyomi.util.lang.RxCoroutineBridgeKt.awaitSingle(RxCoroutineBridge.kt:1)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at eu.kanade.tachiyomi.ui.player.PlayerActivity$awaitVideoList$1.invokeSuspend(PlayerActivity.kt:6)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: okhttp3.Response.class
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:5)
02-14 18:52:57.223 28396 28540 E StandaloneCoroutine: 	... 39 more
02-14 18:52:57.328 28396 28540 E StandaloneCoroutine: java.lang.Exception
02-14 18:52:57.328 28396 28540 E StandaloneCoroutine: 	at eu.kanade.tachiyomi.extension.api.ExtensionGithubApi$findExtensions$2.invokeSuspend(ExtensionGithubApi.kt:19)
02-14 18:52:57.328 28396 28540 E StandaloneCoroutine: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
02-14 18:52:57.328 28396 28540 E StandaloneCoroutine: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
02-14 18:52:57.328 28396 28540 E StandaloneCoroutine: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
02-14 18:52:57.328 28396 28540 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
02-14 18:52:57.328 28396 28540 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
02-14 18:52:57.328 28396 28540 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
02-14 18:52:57.328 28396 28540 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
02-14 18:52:57.328 28396 28540 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
02-14 18:53:15.861 28396 28541 E StandaloneCoroutine: java.lang.Exception
02-14 18:53:15.861 28396 28541 E StandaloneCoroutine: 	at eu.kanade.tachiyomi.extension.api.ExtensionGithubApi$findExtensions$2.invokeSuspend(ExtensionGithubApi.kt:19)
02-14 18:53:15.861 28396 28541 E StandaloneCoroutine: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
02-14 18:53:15.861 28396 28541 E StandaloneCoroutine: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
02-14 18:53:15.861 28396 28541 E StandaloneCoroutine: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
02-14 18:53:15.861 28396 28541 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
02-14 18:53:15.861 28396 28541 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
02-14 18:53:15.861 28396 28541 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
02-14 18:53:15.861 28396 28541 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
02-14 18:53:15.861 28396 28541 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
```
Seems to suggest the issue is from this [parsing call](https://github.com/jmir1/aniyomi-extensions/blob/master/src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt#L206).

**Comment by ReisR7262** [comment]
Same issue :'(

**Comment by devinbedari** [comment]
@jmir1 thanks a ton for fixing this so quickly <3

**Comment by ShauniBoi** [comment]
Still not working for me
